### PR TITLE
Support "stripped" A records

### PR DESCRIPTION
**Pull request by freeyoung**
This PR adds the support for stripping A records from responses
returned by upstream dns resolver.

### CODE REVIEW

**Comment by lamby** [comment]
What's 70.39.191.139 ? :)

**Comment by freeyoung** [comment]
Good point. Comment added.

**Comment by lamby** [comment]
Thanks. :)

Really appreciate contributions but please always keep high commit quality, running a critical eye over each commit before sending. Its a worthwhile longterm investment inho

**Comment by lamby** [comment]
*long-term investment IMHO and also catches bugs :)

**Pull request merged**
