### PR TITLE
Configurable listening host, listening port and upstream port

### PR DESCRIPTION
**Pull request by freeyoung**
This PR makes listening host, listening port and upstream port
configurable.

### CODE REVIEW

**Comment by lamby** [comment]
Not sure you meant to push this commit? I'm still seeing a bunch of unrelated changes that are also not mentioned in the commit (eg. whitespace changes, import removals, comments added, existed, comments being moved around). Don't have any problem with the changes, just you probably pushed the wrong one :)

**Comment by freeyoung** [comment]
I tend to keep the commit message clean. This PR mainly implements the title of this PR, while other changes (whitespace changes, import removals, additional empty line) are to make PEP8 happy.

Once this PR is merged (hopefully :smile:), I will open anther PR which adds support for stripping A records.

**Comment by lamby** [comment]
> other changes (whitespace changes, import removals, additional empty line) are to make PEP8 happy.

They surely belong in another commit then? I mean, it's a "clean commit message" in that it just sneakily doesn't mention the stuff that might make it unclean!

**Comment by freeyoung** [comment]
Updated.

**Comment by lamby** [comment]
:) :)

**Pull request merged**
